-- 권한 정보 테이블
CREATE TABLE TBL_AUTH
(
    AUTH_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    AUTH_NM NVARCHAR(50) NOT NULL,
    CRT_DT  DATETIME DEFAULT GETDATE(),
    UDT_DT  DATETIME DEFAULT GETDATE(),
    CRT_ID  VARCHAR(20),
    UDT_ID  VARCHAR(20)
);

-- 메뉴 테이블
CREATE TABLE TBL_MENU
(
    MENU_ID     VARCHAR(20)  NOT NULL,
    MENU_NM     NVARCHAR(50) NOT NULL,
    MENU_URL    VARCHAR(200) NOT NULL,
    PRT_MENU_ID VARCHAR(20)  NOT NULL,
    LVL         INT          NOT NULL,
    LEAF_YN     CHAR(1)      NOT NULL,
    CRT_DT      DATETIME DEFAULT GETDATE(),
    UDT_DT      DATETIME DEFAULT GETDATE(),
    CRT_ID      VARCHAR(20),
    UDT_ID      VARCHAR(20),
    PRIMARY KEY (MENU_ID, PRT_MENU_ID)
);

-- 메뉴 권한 테이블
CREATE TABLE TBL_MENU_AUTH
(
    MENU_ID VARCHAR(20) NOT NULL,
    AUTH_ID VARCHAR(20) NOT NULL,
    CRT_DT  DATETIME DEFAULT GETDATE(),
    UDT_DT  DATETIME DEFAULT GETDATE(),
    CRT_ID  NVARCHAR(20),
    UDT_ID  NVARCHAR(20),
    PRIMARY KEY (MENU_ID, AUTH_ID)
);

-- 사용자 정보 테이블
CREATE TABLE TBL_USER
(
    USR_ID      VARCHAR(20)  NOT NULL PRIMARY KEY,
    USR_EMAIL   VARCHAR(50)  NOT NULL,
    PWD         VARCHAR(500) NOT NULL,
    USR_NM      NVARCHAR(50) NOT NULL,
    JUMIN       VARCHAR(500) NOT NULL,
    PHONE       VARCHAR(500) NOT NULL,
    ADDR1       NVARCHAR(50) NOT NULL,
    ADDR2       VARCHAR(500) NOT NULL,
    REMARK      NVARCHAR(200),
    USR_AUTH_ID VARCHAR(50),
    LAST_LOG_DT DATETIME              DEFAULT GETDATE(),
    LAST_PWD_DT DATETIME              DEFAULT GETDATE(),
    DEL_YN      CHAR(1)      NOT NULL DEFAULT 'N',
    USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y',
    CRT_DT      DATETIME              DEFAULT GETDATE(),
    UDT_DT      DATETIME              DEFAULT GETDATE(),
    CRT_ID      VARCHAR(20),
    UDT_ID      VARCHAR(20)
);

-- 공통 코드 테이블
CREATE TABLE TBL_COM_CD
(
    PRT_CD_ID VARCHAR(20) NOT NULL,
    CD_ID     VARCHAR(20) NOT NULL,
    LVL       INT,
    CD_NM     NVARCHAR(20) NOT NULL,
    DEL_YN    CHAR(1)     NOT NULL DEFAULT 'N',
    USE_YN    CHAR(1)     NOT NULL DEFAULT 'Y',
    CRT_DT    DATETIME             DEFAULT GETDATE(),
    UDT_DT    DATETIME             DEFAULT GETDATE(),
    CRT_ID    VARCHAR(20),
    UDT_ID    VARCHAR(20),
    PRIMARY KEY (PRT_CD_ID, CD_ID)
);



